# Schema for the configuration files of the YMCA360 Livestreams submodule.

yusaopeny_ymca360_livestreams.settings:
  type: config_object
  label: 'YMCA360 Livestreams settings'
  mapping:
    cron:
      type: mapping
      label: 'Automatic sync'
      mapping:
        enable_cron:
          type: boolean
          label: 'Enable sync on cron runs'
